language: python
python:
  - "3.8"
# command to install dependencies
#install:
before_script:
  - easy_install distribute
  - pip install -r requirements.txt
# command to run tests
script:
  - python src/test_basic.py
